development:
  adapter: postgresql
  encoding: unicode
  database: jumping_rabbit
  pool: 5
  username: vagrant

test:
  adapter: postgresql
  encoding: unicode
  database: jumping_rabbit_test
  pool: 5
  username: vagrant
